extends Resource
class_name SuitStatLevelRule

@export_category("Rule")
## Display name for easier inspector organization.
@export var rule_name := ""

## First level where this rule can trigger.
@export_range(1, 100) var start_level := 1

## Last level where this rule can trigger.
@export_range(1, 100) var end_level := 100

## Rule repeats every X levels.
@export_range(1, 100) var repeat_every_levels := 1

## Higher priority rules are calculated first.
@export var priority := 0

## If true, this rule also triggers exactly at start_level.
@export var include_start_level := true

@export_category("Bonuses")
## Stat bonuses applied every time this rule triggers.
@export var bonuses: Array[SuitStatBonus] = []


## Returns true if this rule should trigger at the given suit level.
func should_trigger_at_level(level: int) -> bool:
	if level < start_level:
		return false

	if level > end_level:
		return false

	if level == start_level:
		return include_start_level

	return (level - start_level) % repeat_every_levels == 0


## Returns how many times this rule has triggered up to the given suit level.
func get_trigger_count(current_level: int) -> int:
	var trigger_count := 0

	for level in range(1, current_level + 1):
		if should_trigger_at_level(level):
			trigger_count += 1

	return trigger_count


## Returns all stat bonuses generated by this rule up to the given suit level.
func get_total_bonus_dict(current_level: int) -> Dictionary:
	var result := {}
	var trigger_count := get_trigger_count(current_level)

	if trigger_count <= 0:
		return result

	for bonus in bonuses:
		if not is_instance_valid(bonus):
			continue

		var stat_key := bonus.get_stat_key()
		var value := bonus.get_value() * float(trigger_count)

		if not result.has(stat_key):
			result[stat_key] = 0.0

		result[stat_key] += value

	return result
